#!/usr/bin/env bun
/**
 * scripts/generate-input-data.ts
 *
 * Generates a synthetic input CSV for testing the ANA app validator.
 *
 * Rules:
 *   - Preference 3 indicators are never filled (always left empty).
 *   - Preference 1 indicators are filled with probability P1 (default 0.7).
 *   - Preference 2 indicators are filled with probability P2 (default 0.4).
 *   - Values are drawn from realistic ranges that respect each indicator's type.
 *   - 50 unique UOAs are generated by default.
 *
 * Usage:
 *   bun ./scripts/generate-input-data.ts [--out <path>] [--uoas <n>] [--seed <n>]
 *                                         [--p1 <0-1>] [--p2 <0-1>] [--help]
 *
 * Output: static/data/input_good_50.csv  (or --out path)
 */

import fs from 'fs';
import path from 'path';
import type { ReferenceRoot } from '../src/lib/types/structure';

// ── Defaults ──────────────────────────────────────────────────────────────────

const OUT_DEFAULT = path.join(process.cwd(), 'static', 'data', 'input_good_50.csv');
const INDICATORS_JSON = path.join(process.cwd(), 'static', 'data', 'reference.json');

const filter1_VALUES = ['North', 'South', 'East', 'West', 'Centre'];
const filter2_VALUES = ['Hosts', 'IDPs', 'Refugees'];

// ── CLI ───────────────────────────────────────────────────────────────────────

interface Args {
	out: string;
	uoas: number;
	seed: number;
	p1: number;
	p2: number;
	filter1: boolean;
	filter2: boolean;
	help: boolean;
}

function parseArgs(argv: string[]): Args {
	let out = OUT_DEFAULT;
	let uoas = 50;
	let seed = 42;
	let p1 = 0.7;
	let p2 = 0.4;
	let filter1 = true;
	let filter2 = true;
	let help = false;

	for (let i = 0; i < argv.length; i++) {
		if (argv[i] === '--help' || argv[i] === '-h') help = true;
		else if (argv[i] === '--out' && argv[i + 1]) out = path.resolve(argv[++i]);
		else if (argv[i] === '--uoas' && argv[i + 1]) uoas = Math.max(1, parseInt(argv[++i], 10));
		else if (argv[i] === '--seed' && argv[i + 1]) seed = parseInt(argv[++i], 10);
		else if (argv[i] === '--p1' && argv[i + 1])
			p1 = Math.min(1, Math.max(0, parseFloat(argv[++i])));
		else if (argv[i] === '--p2' && argv[i + 1])
			p2 = Math.min(1, Math.max(0, parseFloat(argv[++i])));
		else if (argv[i] === '--filter1') filter1 = true;
		else if (argv[i] === '--no-filter1') filter1 = false;
		else if (argv[i] === '--filter2') filter2 = true;
		else if (argv[i] === '--no-filter2') filter2 = false;
	}

	return { out, uoas, seed, p1, p2, filter1, filter2, help };
}

// ── Seeded PRNG (LCG) ─────────────────────────────────────────────────────────

class Rng {
	private state: number;

	constructor(seed: number) {
		this.state = seed >>> 0;
	}

	/** Returns a float in [0, 1) */
	next(): number {
		// Numerical Recipes LCG
		this.state = (Math.imul(1664525, this.state) + 1013904223) >>> 0;
		return this.state / 0x100000000;
	}

	/** Uniform float in [lo, hi], rounded to `dp` decimal places */
	float(lo: number, hi: number, dp = 2): number {
		return +(lo + this.next() * (hi - lo)).toFixed(dp);
	}

	/** Uniform integer in [lo, hi] (inclusive) */
	int(lo: number, hi: number): number {
		return lo + Math.floor(this.next() * (hi - lo + 1));
	}

	/** Returns true with probability p */
	bool(p: number): boolean {
		return this.next() < p;
	}
}

// ── Value generation by type string ──────────────────────────────────────────

/**
 * Generate a single valid value for the given type string.
 * Ranges are intentionally spread across the full valid domain so
 * the data exercises both low and high ends.
 */
function genValue(type: string | null, rng: Rng): string {
	const t = (type ?? '').trim();

	switch (t) {
		// ── half-open [0, +∞) ────────────────────────────────────────────────
		case 'num[0+]':
			// mortality-style rates: mostly 0–8, occasionally higher
			return String(rng.float(0.01, 8.0, 2));

		case 'int[0+]':
			// counts: e.g. number of facilities, caseloads
			return String(rng.int(0, 500));

		// ── proportions [0, 1] ───────────────────────────────────────────────
		case 'num[0:1]':
			return String(rng.float(0.02, 0.98, 2));

		case 'int[0:1]':
			// binary: 0 or 1, slightly biased toward 1
			return String(rng.bool(0.6) ? 1 : 0);

		// ── special closed intervals ─────────────────────────────────────────
		case 'num[0:7]':
			return String(rng.float(0.1, 6.9, 1));

		case 'num[0:24]':
			return String(rng.float(0.5, 23.5, 1));

		case 'int[1:5]':
			return String(rng.int(1, 5));

		// ── unconstrained num ────────────────────────────────────────────────
		case 'num':
			// % change: can be negative or well above 1
			return String(rng.float(-5.0, 10.0, 2));

		// ── no type / unknown → finite number ────────────────────────────────
		default:
			return String(rng.float(0, 1, 2));
	}
}

// ── Indicator metadata collected from JSON ────────────────────────────────────

interface IndMeta {
	code: string;
	type: string | null;
	preference: number;
}

function loadIndicators(jsonPath: string): IndMeta[] {
	if (!fs.existsSync(jsonPath)) {
		console.error(`Error: reference.json not found at ${jsonPath}`);
		process.exit(2);
	}
	const root = JSON.parse(fs.readFileSync(jsonPath, 'utf-8')) as ReferenceRoot;
	const out: IndMeta[] = [];
	for (const sys of root.systems)
		for (const fac of sys.factors)
			for (const sf of fac.sub_factors)
				for (const ind of sf.indicators)
					for (const met of ind.metrics)
						out.push({ code: met.metric, type: met.type ?? null, preference: met.preference });
	return out;
}

// ── CSV builder ───────────────────────────────────────────────────────────────

function buildCsv(inds: IndMeta[], args: Args): string {
	const { uoas, seed, p1, p2, filter1, filter2 } = args;
	const rng = new Rng(seed);

	const header = filter1
		? ['uoa', 'filter1', 'filter2', ...inds.map((i) => i.code)]
		: ['uoa', 'filter2', ...inds.map((i) => i.code)];
	const lines: string[] = [header.join(',')];

	for (let r = 1; r <= uoas; r++) {
		const uoa = 'uoa' + String(r).padStart(2, '0');
		const cells: string[] = filter1
			? [
					uoa,
					filter1_VALUES[rng.int(0, filter1_VALUES.length - 1)],
					filter2_VALUES[rng.int(0, filter2_VALUES.length - 1)]
				]
			: [uoa];

		for (const ind of inds) {
			// Preference 3: always empty
			if (ind.preference === 3) {
				cells.push('');
				continue;
			}

			// Preference 1: fill with probability p1
			// Preference 2: fill with probability p2
			const fillProb = ind.preference === 1 ? p1 : p2;
			if (!rng.bool(fillProb)) {
				cells.push('');
				continue;
			}

			cells.push(genValue(ind.type, rng));
		}

		lines.push(cells.join(','));
	}

	return lines.join('\n') + '\n';
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main(): void {
	const args = parseArgs(process.argv.slice(2));

	if (args.help) {
		console.log(
			`
Usage: bun ./scripts/generate-input-data.ts [options]

Options:
  --out      <path>   Output CSV path  (default: static/data/input_good_50.csv)
  --uoas     <n>      Number of UOAs   (default: 50)
  --seed     <n>      PRNG seed        (default: 42)
  --p1       <0–1>    Fill probability for preference-1 indicators (default: 0.90)
  --p2       <0–1>    Fill probability for preference-2 indicators (default: 0.70)
  --no-filter1        Omit the filter1 region column (included by default)
  --no-filter2        Omit the filter2 region column (included by default)
  --help              Show this help

Notes:
  - Preference-3 indicators are always left empty.
  - Values respect each indicator's type constraint (num[0+], num[0:1],
    int[0:1], int[0+], int[1:5], num[0:7], num[0:24], num, …).
`.trim()
		);
		process.exitCode = 0;
		return;
	}

	console.log(`Loading indicators from: ${INDICATORS_JSON}`);
	const inds = loadIndicators(INDICATORS_JSON);

	const pref1 = inds.filter((i) => i.preference === 1).length;
	const pref2 = inds.filter((i) => i.preference === 2).length;
	const pref3 = inds.filter((i) => i.preference === 3).length;
	console.log(`Indicators: ${inds.length} total  (pref1=${pref1}, pref2=${pref2}, pref3=${pref3})`);
	console.log(`Fill probabilities: pref1=${args.p1}, pref2=${args.p2}, pref3=0 (always empty)`);
	console.log(
		`UOAs: ${args.uoas}  |  Seed: ${args.seed}  |  filter1: ${args.filter1} | filter2:${args.filter2}`
	);

	const csv = buildCsv(inds, args);

	fs.mkdirSync(path.dirname(args.out), { recursive: true });
	fs.writeFileSync(args.out, csv, 'utf-8');

	const lines = csv.split('\n').filter(Boolean).length - 1; // exclude header
	console.log(`\nWrote ${lines} data rows → ${args.out}`);
	process.exitCode = 0;
}

main();
